### PR TITLE
Java compatibility

### PR DESCRIPTION
**Pull request by lukepalmer**

### CODE REVIEW

**Comment by lukepalmer** [comment]
An explanation. I had to do a bit more monkeying than expected.

- Everything revolves around @varargs, which (apparently) has some issues on older scala
- New scala means new akka which means JDK 8 only
- You previously had support for JDK 6 and 7
- JDK 8 is fine with me, as akka is vastly improved on the current version 
- The JZMQ build has (apparently) changed since this was last built.  Native libs are still being built via travis but the JAR is now being sourced from maven.

**Comment by chrisdinn** [comment]
My main concern is that it's probably a little early to drop Java 7 support.

**Comment by lukepalmer** [comment]
@chrisdinn That does make sense. 

To address, my suggestion would be that we have SBT only run the proposed Java test when building on JDK8, still running scala tests on all builds.

This makes everything continue to work as-is for scala on older JDKs. Anyone writing akka in java is going to want JDK8 anyways (as it is greatly improved).

I can give this a try over the weekend if that sounds good.

**Comment by chrisdinn** [comment]
That sounds like a reasonable compromise.

I don't expect anyone to be on Java 7 by choice, but as far as I can tell it's not in Debian yet so we're not ready to make it the new default.

**Comment by jasongoodwin** [comment]
I published the artifact to sonatype and made a PR to change the build file
appropriately.

I'll review the java items over the weekend.

**Comment by lukepalmer** [comment]
Did the following:

1. travis bulid runs both JDK 7 and 8
1. SBT only looks at java on JDK 8
1. Moved jzmq binding via maven to compile scope. Much nicer for anyone developing in an IDE but nobody is forced to use it as a transitive dependency.
1. Removed TestUtils and added akka.SocketUtil.temporaryServerAddress
1. Made a few timeouts configurable and set high values for tests as I was seeing the tests be really unreliable in travis

**Comment by jasongoodwin** [comment]
First, thanks again for taking this on! It's cool that there weren't many items that needed to be changed.

I'll have to defer on the dependency item - I'm hoping @damienlevin or @chrisdinn can chime in. Here is what I'm thinking though: I like the approach of using the managed bindings. I'm just cautious as I'm not sure if there are other use cases where people might want to have control over jzmq version. There have been commits on jzmq recently so it's active. The documentation describes setting up jzmq in the environment so I'm also wondering if there would be impact to existing users who have set up their environments already. It's easy for users to add a dependency to their project. It's more work to remove them. I'm not sure if these concerns are real issues though. 

If we remove the dependency, we can document it as an option - it's much easier to get up and running if you're trying to take zeromq for a spin than building it and getting it on the path correctly.

**Comment by lukepalmer** [comment]
Great let me know. This is just the bindings which are pretty thin (and required for this to even build) so hopefully we can pull from maven.

To be clear, this is not pulling libjzmq / libzmq from maven.  That's what https://github.com/lukepalmer/zeromq-native is for, which appears to be working well with this project if you place it in test scope.

Also a note: struggling to get passing builds due to travis-ci/travis-ci/#5227 which is not actually fixed yet. Hopefully soon.

**Comment by lukepalmer** [comment]
Intentionally closing and re-opening to trigger build as requested in travis-ci/travis-ci#5669

**Comment by jasongoodwin** [comment]
Hey Luke, I talked to the team about the dependency and everyone is on the same page that it's better to leave it out. We'd like to target being able to support the native java implementation JeroMQ one day for quick trials without a full zeromq install but still let people easily use the more performant native implementation w/ jzmq.
A good compromise would be to improve the documentation to let users know that they can use the jzmq dependency instead of doing the full install of jzmq which is a pain to get right. Doing that greatly simplifies configuration needed for people who want to try the library out and should be sufficient to get the same ease of use.

**Comment by lukepalmer** [comment]
Ok, understandable.

The only hangup is that trunk doesn't build in travis as the structure of jzmq has changed. I think I know how to address and will give it a shot.

**Comment by jasongoodwin** [comment]
Ya for jzmq there is a sh script that builds and places the jar - I think
it should be relatively easy to fix. I can have a look at it tonight as
well.

**Pull request closed without merging**
